const provinceStateList = [
  "Alberta",
  "British Columbia",
  "Manitoba",
  "New Brunswick",
  "Newfoundland",
  "Nova Scotia",
  "Northwest Territories",
  "Nunavut",
  "Ontario",
  "Prince Edward Island",
  "Quebec",
  "Saskatchewan",
  "Yukon Territory",
  "Other",
  "Alaska",
  "Alabama",
  "Arkansas",
  "Arizona",
  "California",
  "Colorado",
  "Conneticut",
  "District of Columbia",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Iowa",
  "Idaho",
  "Illinois",
  "Indiana",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Massachussets",
  "Maryland",
  "Maine",
  "Michigan",
  "Minnesota",
  "Missouri",
  "Mississippi",
  "Montana",
  "North Carolina",
  "North Dakota",
  "Nebraska",
  "New Hampshire",
  "New Mexico",
  "Nevada",
  "New York",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Virginia",
  "Vermont",
  "Washington",
  "Wisconsin",
  "West Verginia",
  "Wyoming",
  "American Samoa",
  "Federated States of Micronesia",
  "Guam",
  "Marshall Islands",
  "Northen Mariana Islands",
  "Puerto Rico",
  "Palau",
  "Virgin Islands",
];

const countryList = [
  { name: "Afghanistan", code: "AF" },
  { name: "Aland Islands", code: "AX" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "American Samoa", code: "AS" },
  { name: "Andorra", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Anguilla", code: "AI" },
  { name: "Antarctica", code: "AQ" },
  { name: "Antigua and Barbuda", code: "AG" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Aruba", code: "AW" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bahamas", code: "BS" },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY" },
  { name: "Belgium", code: "BE" },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bermuda", code: "BM" },
  { name: "Bhutan", code: "BT" },
  { name: "Bolivia", code: "BO" },
  { name: "Bonaire, Sint Eustatius and Saba", code: "BQ" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Botswana", code: "BW" },
  { name: "Bouvet Island", code: "BV" },
  { name: "Brazil", code: "BR" },
  { name: "British Indian Ocean Territory", code: "IO" },
  { name: "Brunei Darussalam", code: "BN" },
  { name: "Bulgaria", code: "BG" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Cambodia", code: "KH" },
  { name: "Cameroon", code: "CM" },
  { name: "Canada", code: "CA" },
  { name: "Cape Verde", code: "CV" },
  { name: "Cayman Islands", code: "KY" },
  { name: "Central African Republic", code: "CF" },
  { name: "Chad", code: "TD" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN" },
  { name: "Christmas Island", code: "CX" },
  { name: "Cocos (Keeling) Islands", code: "CC" },
  { name: "Colombia", code: "CO" },
  { name: "Comoros", code: "KM" },
  { name: "Congo", code: "CG" },
  { name: "Congo, Democratic Republic of the Congo", code: "CD" },
  { name: "Cook Islands", code: "CK" },
  { name: "Costa Rica", code: "CR" },
  { name: "Cote D'Ivoire", code: "CI" },
  { name: "Croatia", code: "HR" },
  { name: "Cuba", code: "CU" },
  { name: "Curacao", code: "CW" },
  { name: "Cyprus", code: "CY" },
  { name: "Czech Republic", code: "CZ" },
  { name: "Denmark", code: "DK" },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "Dominican Republic", code: "DO" },
  { name: "Ecuador", code: "EC" },
  { name: "Egypt", code: "EG" },
  { name: "El Salvador", code: "SV" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Eritrea", code: "ER" },
  { name: "Estonia", code: "EE" },
  { name: "Ethiopia", code: "ET" },
  { name: "Falkland Islands (Malvinas)", code: "FK" },
  { name: "Faroe Islands", code: "FO" },
  { name: "Fiji", code: "FJ" },
  { name: "Finland", code: "FI" },
  { name: "France", code: "FR" },
  { name: "French Guiana", code: "GF" },
  { name: "French Polynesia", code: "PF" },
  { name: "French Southern Territories", code: "TF" },
  { name: "Gabon", code: "GA" },
  { name: "Gambia", code: "GM" },
  { name: "Georgia", code: "GE" },
  { name: "Germany", code: "DE" },
  { name: "Ghana", code: "GH" },
  { name: "Gibraltar", code: "GI" },
  { name: "Greece", code: "GR" },
  { name: "Greenland", code: "GL" },
  { name: "Grenada", code: "GD" },
  { name: "Guadeloupe", code: "GP" },
  { name: "Guam", code: "GU" },
  { name: "Guatemala", code: "GT" },
  { name: "Guernsey", code: "GG" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Guyana", code: "GY" },
  { name: "Haiti", code: "HT" },
  { name: "Heard Island and Mcdonald Islands", code: "HM" },
  { name: "Holy See (Vatican City State)", code: "VA" },
  { name: "Honduras", code: "HN" },
  { name: "Hong Kong", code: "HK" },
  { name: "Hungary", code: "HU" },
  { name: "Iceland", code: "IS" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran, Islamic Republic of", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE" },
  { name: "Isle of Man", code: "IM" },
  { name: "Israel", code: "IL" },
  { name: "Italy", code: "IT" },
  { name: "Jamaica", code: "JM" },
  { name: "Japan", code: "JP" },
  { name: "Jersey", code: "JE" },
  { name: "Jordan", code: "JO" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kiribati", code: "KI" },
  { name: "Korea, Democratic People's Republic of", code: "KP" },
  { name: "Korea, Republic of", code: "KR" },
  { name: "Kosovo", code: "XK" },
  { name: "Kuwait", code: "KW" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: "Lao People's Democratic Republic", code: "LA" },
  { name: "Latvia", code: "LV" },
  { name: "Lebanon", code: "LB" },
  { name: "Lesotho", code: "LS" },
  { name: "Liberia", code: "LR" },
  { name: "Libyan Arab Jamahiriya", code: "LY" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "Macao", code: "MO" },
  { name: "Macedonia, the Former Yugoslav Republic of", code: "MK" },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malaysia", code: "MY" },
  { name: "Maldives", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Marshall Islands", code: "MH" },
  { name: "Martinique", code: "MQ" },
  { name: "Mauritania", code: "MR" },
  { name: "Mauritius", code: "MU" },
  { name: "Mayotte", code: "YT" },
  { name: "Mexico", code: "MX" },
  { name: "Micronesia, Federated States of", code: "FM" },
  { name: "Moldova, Republic of", code: "MD" },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN" },
  { name: "Montenegro", code: "ME" },
  { name: "Montserrat", code: "MS" },
  { name: "Morocco", code: "MA" },
  { name: "Mozambique", code: "MZ" },
  { name: "Myanmar", code: "MM" },
  { name: "Namibia", code: "NA" },
  { name: "Nauru", code: "NR" },
  { name: "Nepal", code: "NP" },
  { name: "Netherlands", code: "NL" },
  { name: "Netherlands Antilles", code: "AN" },
  { name: "New Caledonia", code: "NC" },
  { name: "New Zealand", code: "NZ" },
  { name: "Nicaragua", code: "NI" },
  { name: "Niger", code: "NE" },
  { name: "Nigeria", code: "NG" },
  { name: "Niue", code: "NU" },
  { name: "Norfolk Island", code: "NF" },
  { name: "Northern Mariana Islands", code: "MP" },
  { name: "Norway", code: "NO" },
  { name: "Oman", code: "OM" },
  { name: "Pakistan", code: "PK" },
  { name: "Palau", code: "PW" },
  { name: "Palestinian Territory, Occupied", code: "PS" },
  { name: "Panama", code: "PA" },
  { name: "Papua New Guinea", code: "PG" },
  { name: "Paraguay", code: "PY" },
  { name: "Peru", code: "PE" },
  { name: "Philippines", code: "PH" },
  { name: "Pitcairn", code: "PN" },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Puerto Rico", code: "PR" },
  { name: "Qatar", code: "QA" },
  { name: "Reunion", code: "RE" },
  { name: "Romania", code: "RO" },
  { name: "Russian Federation", code: "RU" },
  { name: "Rwanda", code: "RW" },
  { name: "Saint Barthelemy", code: "BL" },
  { name: "Saint Helena", code: "SH" },
  { name: "Saint Kitts and Nevis", code: "KN" },
  { name: "Saint Lucia", code: "LC" },
  { name: "Saint Martin", code: "MF" },
  { name: "Saint Pierre and Miquelon", code: "PM" },
  { name: "Saint Vincent and the Grenadines", code: "VC" },
  { name: "Samoa", code: "WS" },
  { name: "San Marino", code: "SM" },
  { name: "Sao Tome and Principe", code: "ST" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia", code: "RS" },
  { name: "Serbia and Montenegro", code: "CS" },
  { name: "Seychelles", code: "SC" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Singapore", code: "SG" },
  { name: "Sint Maarten", code: "SX" },
  { name: "Slovakia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "Solomon Islands", code: "SB" },
  { name: "Somalia", code: "SO" },
  { name: "South Africa", code: "ZA" },
  { name: "South Georgia and the South Sandwich Islands", code: "GS" },
  { name: "South Sudan", code: "SS" },
  { name: "Spain", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sudan", code: "SD" },
  { name: "Suriname", code: "SR" },
  { name: "Svalbard and Jan Mayen", code: "SJ" },
  { name: "Swaziland", code: "SZ" },
  { name: "Sweden", code: "SE" },
  { name: "Switzerland", code: "CH" },
  { name: "Syrian Arab Republic", code: "SY" },
  { name: "Taiwan, Province of China", code: "TW" },
  { name: "Tajikistan", code: "TJ" },
  { name: "Tanzania, United Republic of", code: "TZ" },
  { name: "Thailand", code: "TH" },
  { name: "Timor-Leste", code: "TL" },
  { name: "Togo", code: "TG" },
  { name: "Tokelau", code: "TK" },
  { name: "Tonga", code: "TO" },
  { name: "Trinidad and Tobago", code: "TT" },
  { name: "Tunisia", code: "TN" },
  { name: "Turkey", code: "TR" },
  { name: "Turkmenistan", code: "TM" },
  { name: "Turks and Caicos Islands", code: "TC" },
  { name: "Tuvalu", code: "TV" },
  { name: "Uganda", code: "UG" },
  { name: "Ukraine", code: "UA" },
  { name: "United Arab Emirates", code: "AE" },
  { name: "United Kingdom", code: "GB" },
  { name: "United States", code: "US" },
  { name: "United States Minor Outlying Islands", code: "UM" },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Vanuatu", code: "VU" },
  { name: "Venezuela", code: "VE" },
  { name: "Viet Nam", code: "VN" },
  { name: "Virgin Islands, British", code: "VG" },
  { name: "Virgin Islands, U.s.", code: "VI" },
  { name: "Wallis and Futuna", code: "WF" },
  { name: "Western Sahara", code: "EH" },
  { name: "Yemen", code: "YE" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
];

const data = {
  title: "Intake Form Questionnaire",
  questions: [
    {
      id: "1",
      question: "Select all that apply",
      type: "checkbox",
      choices: [
        "Import Into Canada",
        "Import Into the US",
        "Ship freight",
        "Speak With a Trade Advisor",
        "Other",
      ],
    },
    {
      id: "2",
      question: "This is my first time importing",
      type: "radioButton",
      choices: ["Yes", "No"],
    },
    {
      id: "3",
      question: "My goods will be for ",
      type: "radioButton",
      choices: ["Personal use", "Commercial use"],
    },
    {
      id: "4",
      question: "Are you importing a:",
      type: "radioButton",
      choices: [
        "Dog/cat",
        "Horse",
        "Vehicle / Engine / Equipment for onor off-road use",
        "Consumer goods (Art, Antiques, household items)",
        "Other",
      ],
    },
    {
      id: "5",
      question: "The Mode of transportation I plan to use is:",
      type: "radioButton",
      choices: ["Air", "Ocean", "Gound", "Courier"],
    },
    {
      id: "6",
      question: "Point A for my goods is:",
      type: "select",
      choices: countryList,
    },
    {
      id: "7",
      question: "Point B for my goods is:",
      type: "select",
      choices: countryList,
    },
    {
      id: "8",
      question: "My goods will begin their journey on:",
      type: "date",
    },
    {
      id: "9",
      question: "I need to speak with a Trade Advisor about:",
      type: "checkbox",
      choices: [
        "CBSA Assessment and Revenue Management (CARM)",
        "Getting a refund of certain duties, taxes and fees (aka duty drawback)",
        "Reviewing my HS codes in use to ensure the best possible duty rates",
        "Reviewing my Free Trade Agreements in use or new ones available to me",
        "Applying for a binding ruling or advance ruling with customs",
        "Conducting a sample audit",
        "Other",
      ],
    },
    {
      id: "10",
      question: "Neither option applies to me, I want to:",
      type: "text",
    },
    {
      id: "11",
      question: "Get a Quote",
      form: [
        {
          id: "12",
          label: "First Name *",
          type: "text",
        },
        {
          id: "13",
          label: "Last Name *",
          type: "text",
        },
        {
          id: "14",
          label: "Company(if applicable)",
          type: "text",
        },
        {
          id: "15",
          label: "Phone *",
          type: "text",
        },
        {
          id: "16",
          label: "Email Address *",
          type: "text",
        },
        {
          id: "17",
          label: "Please provide any additional details that may help:",
          as: "textarea",
        },
      ],
    },
    {
      id: "18",
      label: "Yes, sign me up.",
      type: "checkbox",
    },
    {
      id: "50",
      title: "Ready To Get Started? Tell Us About Your Pet",
      subtext:
        "Take Our Quiz To Uncover What You Will Need To Get Them Into Canada",
      question: "Let’s call them Fluffy! Are they a dog or a cat?",
      type: "radioButton",
      choices: ["Fluffy is a dog", "Fluffy is a cat"],
    },
    {
      id: "51",
      title: "How will Fluffy be traveling?",
      subtext: "...other than ‘In Style’ of course!",
      question:
        "What mode of transportation are you planning to use to bring your animal into Canada?",
      type: "radioButton",
      choices: ["By Truck", "By Plane"],
    },
    {
      id: "52",
      title: "You will need to hire a Customs Broker",
      titleb: "Your airline carrier may require you to hire a Customs Broker",
      subtext: "Fluffy is rollin' by truck",
      subtextb: "Fluffy is flyin' first class",
      content:
        "Fluffy will need to travel by a licensed and registered ground Transport Carrier. ",
      contentb:
      "Everythidng entering Canada must be declared to Canada Customs (also known as the Canada Border Services Agency).",
      paragraph:
        "Because Fluffy will be unaccompanied by you (*the owner), there are certain requirements that must be met, and processes that must be taken, including a Formal Customs Declaration. The transportation carrier you hire will require you to hire a Customs Broker to make this declaration on your behalf to avoid any delays that may stress poor Fluffy out.",
      paragraphb:
      "When traveling by air, this declaration can be made by the airline on your behalf in some cases.",
      paragraphSecond:
        "*The person who has purchased, adopted, or is the current owner of an animal born or currently residing in a country outside of Canada.",
      paragraphSecondb:
        "However, some airline carriers may require you to hire a Customs Broker to meet the arriving plane at the airport to declare Fluffy to Canada Customs upon arrival in Canada.",
      question:
        "What mode of transportation are you planning to use to bring your animal into Canada?",
      type: "button",
      buttonTitle: "Ready for the Next Step?",
      buttonText:
        "I understand that I must report the animal to Canada Customs, and that I need the services of a Customs Broker to do so.",
    },
    {
      id: "55",
      title: "Import Requirements",
      subtext: "Which characteristics best match Fluffy?",
      content:
        "As per the CFIA website,effective September 28, 2022, importation of commercial dogs from areas at risk for rabies will no longer be allowed entry into Canada.",
      content1:
        "Personal Import: A dog for your home (including service dogs adopted by the owner).",
      content2:
        "Commercial Import: A dog that is for sale, adoption, breeding, show, exhibition, scientific research, animal welfare organization, or service dog unaccompanied by their owner.",
      type: "radioButton",
      choices: [
        "Personal Import (Between 8 weeks to 8 months old)",
        "Personal Import (Older than 8 months)",
        "Commercial Import (Less than 8 months)",
        "Commercial Import (Older than 8 months)",
      ],
    },
    {
      id: "56",
      title: "Import Requirements",

      subtext: "Between 8 weeks to 8 months old",
      subtext1: "Older than 8 months",
      subtext2: "Less than 8 months",
      subtext3: "Under 3 months old",
      subtext4: "Over 3 months old",

      contentTitle: "Arrange Before Arriving at the Border",
      contentTitleSub: "(Recommend 30 days prior)",
      contentTitle2: "At the Border",
      contentTitle3: "After the Border",

      contentBold: "Veterinary Certificate of Health",
      content:
        "(signed by the veterinarian) Issued no more than 72 hours before arrival at the port and must ID the animal, age and confirm it is free of disease and can be transported without undue suffering",

      contentBold1: "Rabies Vaccination Certificate",
      contentBold2: "Formal CBSA (Customs) Entry",
      contentBold3: "Rabies Vaccination",
      contentBold4: "A CFIA Issued Import Permit",
      contentBold5: "Microchipped",
      contentBold6: "Visual Inspection of Animal",
      contentBold7: "Documentation Review",
      contentBold8: "CFIA Veterinarian Inspection at the Port of Entry",
      contentBold9: "Rabies Vaccination within two weeks",

      content1:
        "Dog must have been at least 3 months old at the time of vaccination. Must list expiry date of vaccine",
      content2: "If transported by a hired carrier",

      content3: "If one was not in place at the time of entry",
      content4: "If requested by CBSA",
      content5:
        "As per the CFIA website,effective September 28, 2022, importation of commercial dogs from areas at risk for rabies will no longer be allowed entry into Canada.",

      type: "button",
      buttonText: "I Understand the Import Requirements",
    },
    {
      id: "57",
      title: "Please tell us how we can help you bring Fluffy home?",
      subtext:
        "Great! We have helped hundreds of owners import their pets, just like yours, into Canada, and would love the opportunity to do so for you too. Should you want to move forward with our help, please tell us how you would like to get started.",
      content:
        "*A member of our Client Services Team will reach out to you within the hours of 7:00 am - 6:00 pm Monday through Saturday, Pacific Time.",
      contentTitle1: "Testimonials",
      content1:
        "“What didn’t PCB do for us? This company went far and above the call of duty for us. Not only did they call in a driver on the weekend when they are closed to make our puppy delivery happen, they kept track and kept in touch on the phone to make sure everything went smoothly. The driver was so nice and friendly it put us at ease that our puppy was in good hands. Bottom line this would have not happened especially during covid with out them helping us out. It was a ton of leg work but was made easy with their help. Thankyou Donna and PCB so much! You made a family Christmas dream come true!”",
      content2:
        "“Thank you so very much for your care and support facilitating our recent cross-border transfer. We are eternally grateful for your collective work helping this wee international traveler/pup from her only known home in Kelowna to ours, in Anacortes, just in time to melt our hearts and upend our lives.”",

      type: "radioButton",
      choices: [
        "I am ready (I want to start rignt now)",
        "I'm not ready(I need more information. *Please call me)",
      ],
    },
    {
      id: "59",
      mainTitle:
        "Bring your new furry family member home with a little help from us!",
      subtext:
        "From anywhere across North America, let us help you bring your new family member home.",
      title: "Animal Import Services",
      contentTitle: "Subscribe to PCB emails",
      content:
        "PCB Customs Brokers would like to send you regulatory updates, trade news and event notifications relevant to your business. Your privacy is important to us therefore your email will never be shared. You may unsubscribe at any time. For more information please visit our privacy policy. By providing your email you grant us consent to send you emails for a period of 6 months, beginning from your last business exchange with us under Implied consent, after which you will be removed from our mailing list.",
      testimonial:
        "We’ve just had the best experience getting 3 puppies across the border, Surrey, BC to Blaine, WA. They do the Brokerage work, arrange a driver and all is good. They don't want to distance pet hauls but will take them across, all legal and above board. Puppies are in their hands for about 1 1/2 hours if everyone is in place. Thank you, thank you. - Marnie",
      form: [
        {
          id: "60",
          label: "First Name",
          type: "text",
        },
        {
          id: "61",
          label: "Last Name",
          type: "text",
        },
        {
          id: "62",
          label: "Phone Number",
          type: "text",
        },
        {
          id: "63",
          label: "Email Address",
          type: "text",
        },
        {
          id: "64",
          label: "Please indicates your preferred method of contact.",
          type: "checkbox",
          choices: ["Phone", "Email"],
        },
        {
          id: "65",
          type: "checkbox",
          choices: ["Yes, sign me up."],
        },
        {
          id: "66",
          type: "button",
          buttonText: "Submit",
        },
      ],
    },
    {
      id: "70",
      mainTitle: "Get Your Pet Into Canada",
      title: "Get Started On Your Pet Import Into Canada",

      subtext:
        "Great! We have helped hundreds of owners import their pets, just like yours, into Canada, and would love the opportunity to do so for you too. Should you want to move forward with our help, please tell us how you would like to get started.",
      content:
        "*A member of our Client Services Team will reach out to you within the hours of 7:00 am - 6:00 pm Monday through Saturday, Pacific Time.",
      contentTitle1: "Testimonials",
      content1:
        "“What didn’t PCB do for us? This company went far and above the call of duty for us. Not only did they call in a driver on the weekend when they are closed to make our puppy delivery happen, they kept track and kept in touch on the phone to make sure everything went smoothly. The driver was so nice and friendly it put us at ease that our puppy was in good hands. Bottom line this would have not happened especially during covid with out them helping us out. It was a ton of leg work but was made easy with their help. Thankyou Donna and PCB so much! You made a family Christmas dream come true!”",
      content2:
        "“Thank you so very much for your care and support facilitating our recent cross-border transfer. We are eternally grateful for your collective work helping this wee international traveler/pup from her only known home in Kelowna to ours, in Anacortes, just in time to melt our hearts and upend our lives.”",

      type: "radioButton",
      choices: [
        "I am ready (I want to start rignt now)",
        "I'm not ready(I need more information. *Please call me)",
      ],
    },
    {
      id: "71",
      mainTitle: "Get Your Pet Into Canada",
      title: "Get Started On Your Pet Import Into Canada",
      step1: [
        {
          title: "1. Power of Attorney",
          content:
            "This allows PCB Customs Brokers to act on your behalf in the importation with CBSA and CFIA.",
          content1:
            "Please note that this form must be signed with a pen. Customs will not accept an e-signature at this time.",
          type: "button",
          buttonText: "Download A Fillable PDF",
        },
        {
          title: "2. Customs Invoice",
          content:
            "Be sure to add the date of birth and weight of your pet(s) in the description field.",
          type: "button",
          buttonText: "Download A Fillable PDF",
        },
      ],
      step2: [
        {
          title:
            "Step 2: Ask for a Transportation Quote (if you don’t already have one secured)",
          content:
            "If you have already booked your carrier, excellent! You can skip Step 2 and fill out the form below to indicate that you do not need a freight quote.",
        },
      ],
    },
    {
      id: "100",
      question: "Reason for horse import:",
      type: "radio",
      choices: [
        "Show",
        "Race",
        "Breeding",
        "Pasterterage",
        "Competition",
        "Training",
      ],
    },
    {
      id: "101",
      question: "Is there any chance the horse will remain in Canada?",
      type: "radio",
      choices: ["Yes", "No"],
    },
    {
      id: "102",
      question: "What is the value of the horse in Canadian funds?",
      label: "$(CAD)",
      type: "text",
    },
    {
      id: "150",
      mainTitle: "Import Fuel Powered Vehicles And Equipment",
      questions: [
        {
          question: "Into Canada (From the USA)",
          type: "radio",
          choices: ["Under 15 Years Old", "Over 15 Years Old", "Tires"]
        },
        {
          question: "Into the USA (From Canada)",
          type: "radio",
          choices: ["Under 25 Years Old", "Over 25 Years Old", "Tires"]
        }
      ]
    },
    {
      id: "151",
      mainTitle: "Import Fuel Powered Vehicles And Equipment",
      subTitle: ["Into Canada (From The USA) > Under 15 Years Old", "Into Canada (From The USA) > Under 15 Years Old", "Into Canada (From The USA) > Tires", "Into The USA (From Canada) > Under 25 Years Old", "Into The USA (From Canada) > Over 25 Years Old", "Into The USA (From Canada) > Tires"],
      questions: 
      [
        {
          question: "Vehicle Type",
          type: "radio",
          choices: [
           "Fuel Powered Forklifts and Self Propelled Ride-on Pallet Jacks(On Road Use)",
           "Heavy Duty Machinery(Excavator, Backhoes, Rock and Articulated Dump Trucks, Crawler Tractor, etc)(Off Road Use)",
           "Heavy Duty Trucks for the Transport of Goods(5 ton cube type vans)(On Road Use)",
           "Mobile Cranes and Special Purpose Motor Vehicles(On Road Use)",
            "Trailer Mounted Equipment(102' in width or less)(On Road Use)",
            "Trailer Mounted Equipment(exceeding 102' in width)(On Road Use)",
            "Truck Tractors and Vehicles(Configured on a Tractor Chassis, Concrete Mixer, Fire Fighting Equipment, etc.)(On Road Use)",
            "Trucks(Pick Up Trucks, Cargo Vans, Passenger Vehicles)(On Road Use)",
            "Fire Fighting Equipment(On Road Use)",
            "Concrete Mixera(On Road Use",
            "Dump Trucks(On Road Use)",
            "Rock and Articulated Dump Trucks(Off Road Use)",
            "Used Pneumatic Tires(On Road Use)",
            "New Pneumatic Tires(On Road Use)",
            "Used Pneumatic Tires(Off Road Use)",
            "New Pneumatic Tires(Off Road Use)",
            "Fuel Powered Forklift(Salvaged/ Rebuilt Title: )",
            "Fuel Powered Generators and other Fuel Powered Equipment(Salvaged/ Rebuilt Title: )",
            "Truck Tractors and Vehicles(Salvaged/ Rebuilt Title: X)",
            "Heavy Duty Trucks for the Transport of Goods(Salvaged/ Rebuilt Title: X)",
            "Rock and Articulated Dump Trucks(Salvaged/ Rebuilt Title: )",
            "Trucks(Salvaged/ Rebuilt Title: X)",
            "Heavy Duty Machinery w/ fuel powered engines(Salvaged/ Rebuilt Title: )"
          ]
        }
      ]
    },
    {
      id: "152",
      mainTitle: "Import Fuel Powered Vehicles And Equipment",
      choice: {
        title: ""
      }
    },
    {
      id: "200",
      question: "Please describe what you would like to import",
      type: "textarea",
    },
    {
      id: "1000",
      form: [
        {
          id: "1001",
          question: "How would you like to receive your quote:",
          type: "checkbox",
          choices: ["Email", "Phone"],
        },
        {
          id: "1002",
          label: "First Name",
          type: "text",
        },
        {
          id: "1003",
          label: "Last Name",
          type: "text",
        },
        {
          id: "1004",
          label: "Phone number",
          type: "text",
        },
        {
          id: "1005",
          label: "Email",
          type: "text",
        },
        {
          id: "1006",
          label: "CASL consent",
          type: "checkbox",
        },
        {
          id: "1007",
          type: "button",
          buttonText: "Submit",
        },
      ],
      content: " Thank you! We will reach out to you with your quote shortly.",
    },
    {
      id: "2000",
      question: "I plan to:",
      type: "radioButton",
      choices: [
        "Only import once",
        "2 - 5 times per year",
        "More than 6 times per year",
      ],
    },
    {
      id: "2001",
      question:
        "Approximately, what is your average value of import for each shipment?",
      type: "text",
      label: "$(CAD)",
    },
    {
      id: "2010",
      title: "Contact",
      question: "Great, may I ask if you have contacted us previously? *",
      type: "radioButton",
      choices: ["Yes", "No"],
    },
    {
      id: "2011",
      question: "How did you hear about us? *",
      type: "select",
      choices: [
        "All in One Network(AIO)",
        "Amazon",
        "Canada Customs",
        "CAP Referral",
        "Car Club",
        "Carrier",
        "Client",
        "Conqueror Network",
        "Customs Broker",
        "Event",
        "Flying Fresh/FFAF Freight",
        "Freight Forwarder",
        "Orphaned PARS/PAPS",
        "Online",
        "Other",
        "Partner",
        "Restructure/Change Ownership",
        "Ritchie Brothers Auctions(RBA)",
        "Sales Call",
        "U.S. Customs",
        "Vendor",
      ],
      AIO: "AIO Location:*",
      Carrier: "Carrier Name:*",
      Client: "Client Name:*",
      Conqueror: "Conqueror Location:*",
      Customs: "Broker Name:*",
      Event: "Event Name:*",
      FFAF: "FFAF Location:*",
      Forwarder: "Forwarder Name:*",
      Other: "How did they hear of us?:*",
      Partner: "Partner Name:*",
      Sales: "Sales Rep Name:*",
      Vendor: "Vendor Name:*",
    },
    {
      id: "2012",
      question: "Incoming Channel *",
      type: "select",
      choices: [
        "Webform",
        "Chat",
        "Email",
        "Phone",
        "Walk-in",
        "Social Media",
        "Blog Comment",
        "Sales Call",
        "CAP Submission",
        "Amazon SPN",
      ],
    },
    {
      id: "2013",
      question: "Whom are we speaking with?",
      label: "First Name *",
      type: "text",
    },
    {
      id: "2014",
      label: "Last Name *",
      type: "text",
    },
    {
      id: "2015",
      label: "Email *",
      type: "text",
    },
    {
      id: "2016",
      label: "What is the best Phone Number to reach you at? *",
      type: "text",
    },
    {
      id: "2020",
      title: "Services of interest and estimates *",
      type: "checkbox",
      choices: [
        "Import Into Canada",
        "Import Into the US",
        "Ship freight",
        "Carrier Services",
        "Trade Advisory Services",
        "Trade Management",
        "Warehousing and Distribution",
        "Other",
      ],
      Other: {
        label: "If other:",
        type: "text",
      },
    },
    {
      id: "2021",
      label: "Account Class *",
      type: "select",
      choices: [
        "Unresponsive",
        "No Opportunity",
        "Personal",
        "D Account(Any$Amount, No Repeat Business",
        "C Account(Up to $10,000)",
        "B Account(Up to $25,000)",
        "A Account(Up to $50,000)",
        "A+ Account(Up to $100,000)",
        "A++ Account(Up to $100,001 or greater)",
      ],
    },
    {
      id: "2040",
      title: "Company",
      label: "Company Name",
      type: "text",
    },
    {
      id: "2041",
      label: "DBA Name",
      type: "text",
    },
    {
      id: "2042",
      label: "Affiliated Companies",
      type: "text",
    },
    {
      id: "2043",
      label: "Billing/Mailing Address",
      label1: "Address1",
      type: "text",
    },
    {
      id: "2044",
      label1: "Address2",
      type: "text",
    },
    {
      id: "2045",
      label: "City",
      type: "text",
    },
    {
      id: "2046",
      label: "Province/State",
      type: "select",
      choices: provinceStateList,
      Other: {
        label: "Other Province/State",
        type: "text",
      },
    },
    {
      id: "2047",
      label: "Postal/Zip Code",
      type: "text",
    },
    {
      id: "2048",
      label: "Country",
      type: "select",
      choices: countryList,
    },
    {
      id: "2049",
      question: "Physical Address same as Billing/Mailing Address?",
      type: "radioButton",
      choices: ["Yes", "No"],
    },
    {
      id: "2050",
      question: "Company Type",
      type: "radioButton",
      choices: [
        "Sole Proprietorship",
        "Partnership",
        "Corporation/Incorporated",
        "Limited (Ltd)",
        "Limited Liability (LLC)",
        "Joint Venture",
      ],
    },
    {
      id: "2051",
      question: "Fax",
      type: "text",
    },
    {
      id: "2052",
      question: "Years in Business",
      type: "text",
    },
    {
      id: "2100",
      title: "Commercial Account",
      questions: [
        {
          id: "2101",
          question: "Are you currently importing?",
          subtext:
            "CSG Note: If the contact filled out a web form, they will have indicated if they are working with a broker. Check this information in the prospecting ticket and answer the next two questions accordingly.",
          type: "radioButton",
          choices: ["Yes", "No"],
        },
        {
          id: "2102",
          question: "What Commodities are you importing?",
          type: "select",
          choices: [
            "Live Animals (horse,dog,cattle,chicks,bull,alpaca,mink)",
            "No",
          ],
        },
        {
          id: "2103",
          question: "Are you importing temporarily?",
          type: "radioButton",
          choices: ["Yes", "No"],
        },
        {
          id: "2104",
          question: "Are they importing as a Non-Resident?",
          type: "radioButton",
          choices: ["Yes", "No"],
        },
        {
          id: "2105",
          question: "Do you have your own importer bond?",
          type: "radioButton",
          choices: ["Yes", "No"],
        },
        {
          id: "2106",
          question: "How many different products will you be importing?",
          type: "text",
        },
        {
          id: "2107",
          question:
            "Approximately how many lines of product on each import/ Invoice?",
          type: "text",
        },
        {
          id: "2108",
          question: "Approximately how many vendors will you be working with?",
          type: "text",
        },
        {
          id: "2109",
          title: "Revenue Projection",
        },
        {
          id: "2110",
          title: "Estimated Volumes",
          subtext:
            "What are your Est. Annual Volumes? This information helps us get surgical with your rates therefore providing you with the best rate possible.",
        },
        {
          id: "2111",
          question: "Estimated Volumes",
          subtext:
            "What are your Est. Annual Volumes? This information helps us get surgical with your rates therefore providing you with the best rate possible.",
        },
        {
          id: "2112",
          question: "Have you made arrangements to move the freight?",
          type: "radioButton",
          choices: ["Yes", "No"],
        },
        {
          id: "2113",
          question: "Carrier",
          type: "text",
        },
        {
          id: "2114",
          question: "Have the goods already been shipped?",
          type: "radioButton",
          choices: ["Yes", "No"],
        },
        {
          id: "2115",
          question: "What mode of transport are they being shipped by?",
          type: "radioButton",
          choices: [
            "Carrier: Highway",
            " Client: Highway",
            "Carrier: Ocean",
            " Client: Rail",
            "Carrier: Air",
            "Courier",
          ],
        },
        {
          id: "2116",
          question: "What country are the goods being made available to you?",
          subtext:
            "For example, are they being shipped to a port, to a fulfillment center or business, where you will then have to arrange further delivery to the ultimate destination?",
          subtext1:
            "Note for CSG: The best freight opportunities exist with incoterms FOB, EXW, and FCA. Use below for laymen's explanations of each. If this importer is shipping by one of these terms, please select the applicable term below.",
          type: "radioButton",
          choices: [
            "FOB Foreign country (Delivered to an ocean port and made available to the importer from there)",
            "FOB Destination country (Delivered to an ocean port and made available to the importer from there)",
            "EXW (Made available to the importer at the sellers/exporters location in a foreign country. Importer is responsible for completing the import documentation)",
            "FCA (Seller/exporter arranges for goods to be loaded on truck or plane and creates import docs. Importer takes over freight from there.)",
            "Unsure/other",
          ],
        },
        {
          id: "2117",
          question: "Ports of crossing",
          type: "checkbox",
          choices: ["West Coast", "East Coast", "Central"],
        },
        {
          id: "2118",
          question:
            "Will you be managing your tariff classification or would you like us to do so on your behalf?",
          subtext:
            " If you manage it, you will need to classify, assign and provide it on the paperwork. You will also be required to keep it updated with any changes. Otherwise, we will classify & assign upon receipt of your paperwork.",
          type: "radioButton",
          choices: ["Client", "Broker"],
        },
        {
          id: "2119",
          question: "Last Database Review Date",
          type: "date",
        },
        {
          id: "2120",
          question:
            "Do you or will you take advantage of Free Trade Agreements?",
          type: "radioButton",
          choices: ["Yes", "No"],
        },
        {
          id: "2121",
          question: "Who prepares your customs documentation?",
          type: "checkbox",
          choices: ["Vendor", "Importer", "Other"],
        },
        {
          id: "2122",
          question:
            "Are you wanting any specific reporting, phone line or communications set up such as an EDI connection or dedicated fax line?",
          type: "checkbox",
          subtext:
            "Upon receipt of your shipment documentation, we will review it to ensure all required data & documents are there. If not, we will reach out to you to obtain them. There is an additional charge for this",
          choices: [
            "Dedicated Fax Number",
            "Dedicated Phone Number",
            "Custom Technology Development",
            "EDI (if yes, questionnaire added to package)",
            "Custom Report (if yes, add request for sample to instructions)",
          ],
        },
        {
          id: "2200",
          title: "Warehouse Services",
          question: "What services are requested?",
          type: "checkbox",
          choices: [
            "Consolidation / De-consolidation Service ",
            "Handling and Warehousing of In-Bond Cargo ",
            "Southbound Services ",
            "Local Delivery ",
            "Load Restructuring ",
            "Re-palletizing or Re-crating ",
            "Vehicle Shipping Services",
          ],
        },
        {
          id: "2300",
          title: "Payment",
          question: "How will they be paying?",
          type: "radioButton",
          choices: [
            "Credit Card",
            "Debit (requires in-person visit to PCB)",
            "On Credit",
            "Wire Payment / Bank Transfer",
          ],
        },
        {
          id: "2400",
          title: "Projections",
          question: "Opportunities for Additional Services?",
          type: "radioButton",
          choices: [
            "Freight Management",
            "Project Management",
            "Canadian Customs Brokerage",
            "U.S. Customs Brokerage",
            "Trade Advisory Services",
            "Warehousing & Distribution",
            "Carrier Services",
            "Other",
          ],
          other: {
            type: "text",
          },
        },
        {
          id: "2401",
          question: "Excellent Lead for Partner Services?",
          type: "checkbox",
          choices: [
            "Small Business Services",
            "EDC",
            "UCanTrade",
            "Surrey Board of Trade",
            "AmCham",
            "Deloitte Tax Law",
            "DBUSA Partner",
            "I.E. Canada",
          ],
        },
        {
          id: "2500",
          title: "Client On-Board Package",
        },
      ],
    },
  ],
};

export default data;
